language: python
python:
  - "3.6"
install:
  - pip install keras>=2.1.5 pandas>=0.23.4 flake8 pytest nltk

stages:
  - test

jobs:
  include:
    - stage: test
      name: linting
      script:
      - flake8 --max-line-length 100
    - stage: test
      name: tests
      script:
      - pytest