language: python
python:
  - "3.6"
install:
  - pip install keras>=2.1.5 pandas>=0.23.4 flake8 pytest

stages:
  - test

jobs:
  include:
    - stage: test
      script:
      - flake8
    - stage: test
      script:
      - pytest